name: Configuration Check
on:
  repository_dispatch:
    types:
      - configuration-check
jobs:
  check:
    name: Run check
    runs-on: ubuntu-latest
    env:
      PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
      FUNCTION: ${{  github.event.client_payload.function }}
      PLATFORM: ${{  github.event.client_payload.platform }}
      BRANCH: ${{  github.event.client_payload.branch }}
    
    steps:
      - name: Send Slack Message
        run: |
          echo 'Hello world'
          echo '${{ env.FUNCTION }} ${{ env.PLATFORM }} ${{ env.BRANCH }}'
