name: Configuration Check
on:
  repository_dispatch:
    types:
      - configuration-check
jobs:
  check:
    name: Run check
    runs-on: ubuntu-latest
    env:
      PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
      USER_NAME: ${{  github.event.client_payload.key1 }}

    steps:
      - name: Send Slack Message
        run: |
          echo 'Hello world'
          echo {{ env.USER_NAME }}
